### ISSUE TITLE
Error in SSR when using Nuxt

### ISSUE THREAD

**Issue by gijo-varghese** [saintplay/vue-swatches#10]
I'm getting an error when I use vue-swatches with Nuxt. The error is `"window not found"`. It's trying to access `window` object, but in SSR, there is no `window`

**Comment by saintplay** [comment]
meanwhile I'm working on solving this

Hopefully this workaround does for you

```
import Swatches from 'vue-swatches/src/Swatches.vue'
```

**Comment by jonathaniqueda** [comment]
I was with same problem and this workaround didnt work :(

**Comment by jonathaniqueda** [comment]
These dependencies were not found:

* !!vue-style-loader?{"sourceMap":true}!css-loader?{"sourceMap":true,"minimize":false,"importLoaders":1,"alias":{"/static":"/Users/iqueda/Projects/fleekUs/balthazar/testing/static","/assets":"/Users/iqueda/Projects/fleekUs/balthazar/testing/assets"}}!../../vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-ccd7c548","scoped":false,"hasInlineConfig":true}!sass-loader?{"sourceMap":true}!../../vue-loader/lib/selector?type=styles&index=0!./Swatches.vue in ./node_modules/vue-swatches/src/Swatches.vue

**Comment by saintplay** [comment]
@jonathaniqueda sorry you are having this problem. This is indeed a build problem.

In order to use the workaround you need to add this dev dependencies

```
npm install --save-dev node-sass sass-loader
```

More info:
https://nuxtjs.org/faq/pre-processors/

**Comment by jonathaniqueda** [comment]
hey @saintplay thansk for that.

I really recommended you use something like that: https://github.com/egoist/vue-no-ssr

I apply it on some plugins. Thanks again!

**Comment by saintplay** [comment]
Vue Swatches 2 is finally out, it have better integration with nuxt.
You can check it here <https://github.com/saintplay/vue-swatches/releases/tag/v2.0.0>
