### ISSUE TITLE
Alternative Text and Text/Label for swatches

### ISSUE THREAD

**Issue by miljko1984** [saintplay/vue-swatches#12]
Firts of all: Hello and thank you for your amazing work.

How can I show names of colors under it, i have my own colors in a nested arrays.

Thanks in advance.

**Comment by miljko1984** [comment]
Ok, no need for rush and thanks for your quick answer :)

**Comment by hatrena** [comment]
I also need this feature. Would be so great. Thanks

**Comment by hatrena** [comment]
@saintplay That would be great :+1:

**Comment by dominikbruechner** [comment]
Hola Diego, 
muchas gracias por tu trabajo :) 
Looking forward to you accessibility solution

**Comment by saintplay** [comment]
Vue Swatches 2 is finally out, it have better support for accessibility.
You can check it here <https://github.com/saintplay/vue-swatches/releases/tag/v2.0.0>
