### ISSUE TITLE
internalValue change cannot be blocked during input event

### ISSUE THREAD

**Issue by JesusCrow** [saintplay/vue-swatches#16]
**Expectations:**
When I provide `@input` event and bind `:value` I expect to control current swatches colour myself. Just like dialogs or any other component out there.

**Realisation:**
Swatches have internal value, which is changed inside of component, so I cannot control this process manually with `@input` event, where I should update the `:value` that i provide to the swatches myself.

**Comment by saintplay** [comment]
Hi, can you provide a code example of what isn't working for you?

**Comment by JesusCrow** [comment]
https://codesandbox.io/s/4863l0n3w7

Using "inline" swatches. This components breaks "props down, events up" flow. Colour should be controlled in parent component. If it's not, you can't add any conditions.

**Comment by saintplay** [comment]
Yes, this also affects the trigger.

Fixed in [v1.0.2](https://github.com/saintplay/vue-swatches/releases/tag/v1.0.2)
