### ISSUE TITLE
Line 95 of src/Swatches.vue v1.0.2 change is missing in NPM's v1.0.2 package

### ISSUE THREAD

**Issue by JaredThomas** [saintplay/vue-swatches#18]
**Issue:**
The change to [line 95 of Swatches.vue of the 1.0.2 release](https://github.com/saintplay/vue-swatches/compare/v1.0.2...master#diff-2099112ae6ee5793dd084caf08040bffR95) is not included when installing that version of the package.  When diffing with that version of the file all of the other changes are appearing which seems strange, and I'm hoping someone else can reproduce this.  This missing change is causing the submit event to be triggered when vue-swatches is used within a form, and would be fixed if Vue's prevent event modifier was included.  An alternative fix would be to use the `type="button"` attribute to override the standard `submit` type.

**Expected result:**
line 95 of Swatches.vue should include Vue's prevent event modifier:
`@click.prevent="onFallbackButtonClick"`

**Actual result:**
line 95 of Swatches.vue does not include Vue's prevent event modifier:
`@click="onFallbackButtonClick"`

**Steps to reproduce:**

1. Create a new directory and initialize as a new NPM package by running `npm init` (accept defaults).
2. Install the latest published version of the vue-swatches package `npm install vue-swatches --save`
3. Confirm in `node_modules/vue-swatches` that the version in package.json is `1.0.2`
4. Open `node_modules/vue-swatches/Swatches.vue` and inspect line 95 and compare to the [v1.0.2 release](https://github.com/saintplay/vue-swatches/compare/v1.0.2...master#diff-2099112ae6ee5793dd084caf08040bffR95) to see the difference.  Look at one of the other lines like [line 70 ](https://github.com/saintplay/vue-swatches/compare/v1.0.2...master#diff-2099112ae6ee5793dd084caf08040bffR70)to see that it does correctly match what was changed in the release.

You can also download the following test package, unzip, and run `npm install` which as you will see in its' package.json will only install vue-swatches 1.0.2:
[vue-swatches-test.zip](https://github.com/saintplay/vue-swatches/files/2870575/vue-swatches-test.zip)

**Comment by JaredThomas** [comment]
I apologize, I see clearly the commit was after v1.0.2 so it just has not been released yet.  Feel free to close or if you have an update on when it might be released let us know.  Thanks again for your work, and sorry for the false alarm.

**Comment by saintplay** [comment]
I just released [v.1.0.3](https://github.com/saintplay/vue-swatches/releases/tag/v1.0.3) for this matter

**Comment by JaredThomas** [comment]
Thanks for your help @saintplay, and for the quick release.
