### ISSUE TITLE
vue-swatches component not getting the value from a variable

### ISSUE THREAD

**Issue by jcjabros** [saintplay/vue-swatches#19]
vue-swatches is working fine the problem is that I have an edit form and I want to pass the value (color in HEX) from a variable to the component as a selected like `value="{{$var->hex_color}}`.

`
      components: { 
        Swatches,
      },
      data:{
        color:'#ffffff',
      },
    });
`

`<swatches v-model="color" colors="text-advanced" value="{{$var->hex_color}}"></swatches>`

When I load the page it shows the default color `#ffffff` instead of the `$var->hex_color`.

**Comment by saintplay** [comment]
Hi, why you are using `v-model` and `value` at the same time?, try using `v-model` only

**Comment by jcjabros** [comment]
> Hi, why you are using `v-model` and `value` at the same time?, try using `v-model` only

Hi, you mean like this `<swatches v-model="{{$var->hex_color}}" colors="text-advanced"></swatches>`
I tried not working.

**Comment by saintplay** [comment]
```
<swatches v-model="color" colors="text-advanced"></swatches>

{
  data:{ color:  "{{$var->hex_color}}" }
}
```

**Comment by saintplay** [comment]
I will close this, due inactive, and this is actually a vue concern
