### ISSUE TITLE
Custom Colors data?

### ISSUE THREAD

**Issue by standfv** [saintplay/vue-swatches#20]
How to custom colors data?
Default:
colors: ["#000000", "#1111111",...]
Now I want:
colors: [ { color: "#000000", text_field: "#555555", background_field: "#999999" ....}, { color: "#111111", text_field: "#555555", background_field: "#999999" ....}]
I can???

**Comment by saintplay** [comment]
Hello,
No you can't do it in this component,

However, you should have a method to get the other relevant data, like this:


```js

function getColorData(color) {
  switch (color) {
     case "#000000": return { text_field: "#555555", background_field: "#999999"  },
     case "#111111": return { text_field: "#555555", background_field: "#999999"  }
  }
```
