### ISSUE TITLE
[doc request] from CDN

### ISSUE THREAD

**Issue by Neon22** [saintplay/vue-swatches#21]
Very much appreciate the work you've done but I am new to Vue and having difficulty integrating.
The Basic example seems to be for a .vue file.
But I am just using the CDN and html/css/js files. So need to define Swatches as a component so I can include it in my vue instance under components.
Could you please add a doc example so I can do something in codepen like this.
E.g.
```
var swatches = {
  template: '<div><swatches v-model="color" /></div>',
  data () {
      return { color: '#1CA085' }
    }
}
var vm = new Vue({
  el: '#app',
	selectedColorHex: '',
  data: pattern_data,
  components: {
    swatches,
  },
```
or maybe its
```
components: {
  'swatches': VueSwatches
}
```

**Comment by Neon22** [comment]
Looking at your new 2.0 branch it might be:
components: {
  Swatches: window['vue-swatches'],
}
but not quite right yet...

**Comment by saintplay** [comment]
Hi, like it's written in the **Basic Usage**

> components: { Swatches }, // window.VueSwatches.default - from CDN

so, you need to import the component like this

```js
{
  components: {
  {
    Swatches: window.VueSwatches.default
  }
}
```

let me know if that solves your problem

**Comment by Neon22** [comment]
yes it does. sorry I did not understand that correctly
