### ISSUE TITLE
How to use v-validate in vue-swatches?

### ISSUE THREAD

**Issue by ranaclyde** [saintplay/vue-swatches#22]
I'm trying to use v-validate through the trigger slot name, but I can not get it to work.

Any ideas?

```js
<Swatches v-model="color.hex" colors="text-advanced">
  <input
     slot="trigger"
     class="input"
     :value="color.hex"
     v-validate="'required'"
     name="Color"
     readonly
  >
</Swatches>
```

Thanks

**Comment by saintplay** [comment]
What library are you using?

**Comment by ranaclyde** [comment]
"vee-validate": "2.2.7" --> https://github.com/baianat/vee-validate

**Comment by saintplay** [comment]
Have you tried the `ValidationProvider` from `vee-validate`.

Here is a example, (I validate to be a email just for demostration)
https://codesandbox.io/embed/vue-swatches-with-vee-validate-vz5c7

Also you don't need a `<input />` to validate.

If you a form, you should validate manually on submit

https://baianat.github.io/vee-validate/guide/components/validation-provider.html#examples
