### ISSUE TITLE
Add support for transparency / alpha

### ISSUE THREAD

**Issue by murdockq** [saintplay/vue-swatches#23]
I am trying to use this do generate a transparent background like

`rgba(0 0 0 0.5)`

right now it only outputs hex values, but would also be nice to have swatches with alpha and output format of rgba for css usage.

**Comment by saintplay** [comment]
What is your use case? What about creating slider to assign transparency?

This would be possible in 2.0 with swatches objects <https://github.com/saintplay/vue-swatches/pull/14>

Right now, you need to find a workaround maybe with **important css**

**Comment by murdockq** [comment]
The use case is to use pre-defined swatches with transparency already defined, that will be used in map overlays that require transparency to be able to see the map underneath the polygon like this:
![map](https://i.stack.imgur.com/L4uaL.jpg)

A short term work around is to just use a hex-to-rgba function and seperate alpha slider, but ideally I would like the transparency to already be defined on the swatch selection without any slider required.

**Comment by saintplay** [comment]
Have you try **rrggbbaa** values

> Hexadecimal notation: #RRGGBB[AA]
> R (red), G (green), B (blue), and A (alpha) are hexadecimal characters (0-9, A-F). A is optional.
> For example, #ff0000 is equivalent to #ff0000ff.

**Comment by murdockq** [comment]
Cool I'll give that a shot, didn't know that was a thing :) . Looks like chrome support happened in 2016.

**Comment by saintplay** [comment]
Me neither, I didn't really think in that format when developing,  hopefully it works out of the box

**Comment by saintplay** [comment]
Tried in <https://codesandbox.io/s/vue-swatches-w-transparency-cgq00>
 and works fine
