### ISSUE TITLE
Open picker on trigger focus

### ISSUE THREAD

**Issue by joelcuevas** [saintplay/vue-swatches#3]
Hello @saintplay!

Is there a way to open the picker when the trigger gets focused? 

This is specially useful when using with a text input (because I want the users could write any color they want, but suggest a few) and using tab to navigate through the form.

Thank you for the nice work!

**Comment by joelcuevas** [comment]
And how about an `$emit('open')` on `showPopover ` as you have on close and blur? :smile:

**Comment by saintplay** [comment]
Yeah, this component doesn't have good support for accessibility. And that's someting I want to change.

I will definitely start with keyboard navigation, so this issue will be addressed soon.

**Comment by joelcuevas** [comment]
Great! Thank you very much.

BTW, I had to do this (not very elegant, but works) to prevent `.vue-swatches` getting an "invisible" focus when pressing tab:

```js
mounted() {
    this.selected = this.color;

    Vue.nextTick(() => {
        $('.vue-swatches', this.$el).attr('tabindex', '-1');
    });
}
```

Nevertheless, didn't manage to make the swatches work seamlessly using only keyboard, so, by the moment, I'm using the default clickable behaviour.

But if you need a hand, let me know. Definitely would love to see this improvements!

**Comment by saintplay** [comment]
Meanwhile, I just remembered

**Gitlab**, for example shows a input to allow the user write a custom color.

![image](https://user-images.githubusercontent.com/9372893/36556546-9291faac-17d3-11e8-8b76-44ff9751b303.png)

Note that the input is **isnside** the popover

This functionality is somewhat written in VueSwatches, but for other reasons I decided to delay this feature.

What do you think, having a input as a "fallback" inside in the Popover?

**Comment by joelcuevas** [comment]
Well, in fact I finally did something like that:

![image](https://user-images.githubusercontent.com/275014/36634179-3744da72-1966-11e8-88a8-deccc13886ab.png)

Of course, in my case the input is not inside the popover, but I guess having a fallback input is not a bad idea at all.

Although the keybord navigation would be a very usefull feature, I'm happy with my current arrangement: the user can navigate to the input and the trigger button without loosing track of where the focus is.

I just would love to be able to apply some "active" class to the trigger button when the popover is open, that's why I previously asked for the `$emit('open')` event. 😄

**Comment by joelcuevas** [comment]
That's great!!!

BTW, if you want to close this issue, it's OK for me. As I said, I've already have a working setup. If you wan't to keep it for future ref, it's OK too. :)
