### ISSUE TITLE
Integrating in asp.Net core application

### ISSUE THREAD

**Issue by Brilbroeder** [saintplay/vue-swatches#37]
We use asp.Net core as the platform to build a web-application and integrate vue.js as a means to enricht the UI. We have been using 3th party vue-components before successfully. We cannot find a way to integrate this one.

Any help would be appreciated.

https://stackoverflow.com/questions/59328739/3th-party-vue-js-component-vue-swatches-error-did-you-register-the-componen

**Comment by saintplay** [comment]
Hi,
related to #21 
Let me know if that solves your problem

**Comment by saintplay** [comment]
closing due inactivity

**Comment by saintplay** [comment]
Just for the record and for people coming here wanting to integrate Vue Swatches in ASP.NET, you can check:
- [Usage in Browser](https://saintplay.github.io/vue-swatches/guide/#usage-in-browser) - easiest way

If you want more efficiency you should donwload the required files and check <https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1>
