### ISSUE TITLE
Swatch value occasionally not set or set to null

### ISSUE THREAD

**Issue by zalom** [saintplay/vue-swatches#39]
Hi @saintplay,
I implemented the swatches as a base color picker component, like so ->
```javascript
<template>
  <div
    class="swatches-wrapper"
  >
    <swatches
      v-model="localColor"
      :colors="colors"
      show-border
      :trigger-style="triggerStyle"
      :exceptions="exceptions"
      exception-mode="hidden"
    />
  </div>
</template>

<script>
import Swatches from 'vue-swatches'

export default {
  name: 'BaseColorPicker',
  components: { Swatches },
  props: {
    color: {
      type: [String, Object],
      default: ''
    },
    exceptions: {
      type: [Array],
      default: function () {
        return []
      }
    }
  },
  model: {
    prop: 'color',
    event: 'colorchange'
  },
  data: () => {
    return {
      colors: [
        '#FFFFFF', '#FFFF00', '#FFA500', '#008000', '#0000FF',
        '#800000', '#000000', '#800080', '#FF0000', ''
      ],
      triggerStyle: {
        width: '42px',
        height: '42px'
      }
    }
  },
  computed: {
    localColor: {
      get: function () {
        let color = this.color
        if (color) {
          color = color.match(/^#/g) ? color : `#${color}`
        }
        else {
          color = ''
        }
        return color
      },
      set: function (value) {
        let newValue
        if (value) {
          newValue = value.slice(1,7)
        }
        else {
          newValue = null
        }
        return this.$emit('colorchange', newValue)
      }
    }
  }
}
</script>
```
and I use that component on multiple places in one dialog, like this ->
```javascript
<BaseColorPicker
  v-model="dataAttr1"
  @colorchange="detectChange1"
/>

// ~//~

<BaseColorPicker
  v-model="dataAttr10"
  @colorchange="detectChange10"
/>
```

The issue I am experiencing is shown on the gif below (larger gif, sorry about that) ->
![vue-swatches-issue-2](https://user-images.githubusercontent.com/4841044/77908513-e79bf600-728b-11ea-910e-35f512efeb21.gif)

I checked all sorts of outcomes and options that I could think of. I didn't try my code in this project, that is the next thing to do, but I was not able to reproduce it in the local build as is.

Any ideas?

**Comment by saintplay** [comment]
Hi, can you create a [Sandbox](https://codesandbox.io/s/vue) or a repository for better inspection?

**Comment by saintplay** [comment]
And also I get why you create a wrapper component, but why using a custom event `colorchange`, you could do everything with `v-model` only

**Comment by zalom** [comment]
Hi @saintplay,
> And also I get why you create a wrapper component, but why using a custom event `colorchange`, you could do everything with `v-model` only

I need to react to that event, so when it happens, I can send an update to the server.

> Hi, can you create a [Sandbox](https://codesandbox.io/s/vue) or a repository for better inspection?

I will try to reproduce it in some way, I don't have much time right now but will certainly give it a go tomorrow or day after tomorrow. I will post it here once it is done.

Do you have any clue about what is going on?

**Comment by saintplay** [comment]
Sorry, I find your pattern a little confusing. Also, as far as I know you can use `v-model` and `@input` at the same time. So `@input` should retrieve you the same functionality as `@colorchange`. Creating a watcher should work too.

For reference, here is a video of Chris Fritz that explains how to create a transparent wrapper:
- https://www.youtube.com/watch?v=7lpemgMhi0k&feature=youtu.be&t=1313

**Comment by zalom** [comment]
OK, I will take a look, thanks!

**Comment by saintplay** [comment]
Closing due inactivity, feel free to reopen with a sandbox
