### ISSUE TITLE
Empty selection

### ISSUE THREAD

**Issue by perezale** [saintplay/vue-swatches#4]
Hi, I'm about to use this picker, have you considered any empty selection / no-color state?

If it's already out there maybe I missed it from the documentation
Thanks!

**Comment by saintplay** [comment]
Hi
This isn't in the documentation,
Would you like to see an option to choose transparent/no-color?

![image](https://user-images.githubusercontent.com/9372893/36998761-06d9f0ac-208c-11e8-9c44-a9c7668c90b0.png)

![image](https://user-images.githubusercontent.com/9372893/36998800-25d9ef20-208c-11e8-905f-a9475ff35db2.png)

What is your use case?

**Comment by perezale** [comment]
Exactly! Im adding a color filter to a list where a list item may not have any color asigned. Id love to help supporting this feature

**Comment by saintplay** [comment]
yeah, I think `NoColor` Slot will be perfect for this use case.

You can make a PR if you want, otherwise I will be shipping this feature and `FallbackInput` slots this weekend.

**Comment by saintplay** [comment]
[v1.0.0](https://github.com/saintplay/vue-swatches/releases/tag/1.0.0) released

**no-color/transparent** swatch can be added with a color with the value of `''`(*empty-string*)
