### ISSUE TITLE
Styling problems

### ISSUE THREAD

**Issue by cristiancundari** [saintplay/vue-swatches#49]
### Simple Mode:
Some css framework uses box-sizing property set globally to border-box. This setting causes the 4th swatch to wraps in the second row because browser calculates the **_vue-swatches__wrapper_** width considering also paddings. This can be solved by adding
`.vue-swatches__wrapper {
    box-sizing: content-box;
}`

Also considering change the wrapper width dynamically when we submit an array of swatches with less than four items, in order to remove the white space on the right side of the last swatch.

### Inline Mode:
When using inline mode there is too much space on the left and on top of the swatches row. This is caused by **_vue-swatches__wrapper_** inline styling which add padding-top and padding-left and also by **_vue-swatches__container_** inline styling which add padding on all side as well as some bottom margin.
Also every **_vue-swatches__swatch_** adds a bottom margin in case of wrapping, but this way remains too much space on the bottom. I think you could add negative margin on the parent container to solve this.

The swatches row should start at the very left of the parent container, without any extra space by default, so it lines up with other contents in the page.

![image](https://user-images.githubusercontent.com/37112275/82507067-9842ab00-9b01-11ea-8576-4be397915434.png)

**Comment by saintplay** [comment]
Great catch, fixed in [v2.1.0](https://github.com/saintplay/vue-swatches/releases/tag/v2.1.0)
