### ISSUE TITLE
Disabled mode

### ISSUE THREAD

**Issue by NikoNagy** [saintplay/vue-swatches#5]
Hello @saintplay, thanks for your awesome picker !

Got a question : Is it possible to disable vue-swtaches globally  with a prop ?

Something like : 
`<vue-swatches v-model="displayColor"
                              :colors="displayColorsAvailable"
                              :disabled="readOnlyMode"/>`

With `readOnlyMode` as a boolean.

**Comment by saintplay** [comment]
Hi,
No. this isn't possible right now!

but it should be easy to implement,
I'll be working on this feature this weekend.

**Comment by saintplay** [comment]
TODO List

- [x] Disable each swatch
- [ ] Disable trigger
- [x] Create test for disabled mode and `inline-mode: true`
- [x] Create test for disabled mode and `inline-mode: false`
- [ ] Add stories to Storybook
- [x] Create an example
- [x] Add this prop to the documentation

**Comment by saintplay** [comment]
@NikoNagy 
I just finished this feature, but I'm planing to release it in *1.0.0* (hopefully this Sunday)
If you want a npm release before that just tell me

**Comment by NikoNagy** [comment]
No problem. But where's the branch gone ?

I'd like to see your improvements, learning wich mistakes I've made on so :)

**Comment by saintplay** [comment]
yeah sorry but I needed to [squash the commits](https://github.com/saintplay/vue-swatches/commit/8307bb50b31220d18e771b590da04a2bae64f978)

You can still see the new changes comparing the branch **1.0.0** with your **fork**

**Comment by NikoNagy** [comment]
Uh... Ok... Not really cool for contributions tracking...

Anyways, thanks.

**Comment by saintplay** [comment]
Yeah, sorry about that, I should squashed directly from the PR.

Version [1.0.0](https://github.com/saintplay/vue-swatches/releases/tag/1.0.0) is available btw.

Please, feel free to add you as a colaborator in the README [section](https://github.com/saintplay/vue-swatches#awsome-contributors)

**Comment by NikoNagy** [comment]
Thanks for the 1.0.0, nice work !

I let you judge if I deserve it 🥇

**Comment by saintplay** [comment]
Yes! of course, that's why I asked :smiley:
