### ISSUE TITLE
Named colors

### ISSUE THREAD

**Issue by neel** [saintplay/vue-swatches#52]
Currently the `color` property acts as the color value as well as the background color of the circle. However I need a separate `value` attribute for named colors. 

I have different themes, and the theme names may not match with a known color name. e.g. volcano may mean a darkish red theme. So I want the value attribute to hold the theme name and the color attribute to store the background color of the circle.

**Comment by saintplay** [comment]
Did you use the label property?

```js
{
  label: 'volcano',
  color: 'red'
}
```

**Comment by neel** [comment]
The label property only shows the name. But the label is not set as the `v-model`. I could set the `label` to volcano if the label is synced with `v-model` instead of the `color` attribute.

**Comment by saintplay** [comment]
I understand your problem now, maybe a `value` property in the swatch object could do the job.
For now, you can do this separating the `v-model` into `:value` and `@input` and do the transformations manually
