### ISSUE TITLE
Show fallback input with custom triggerr

### ISSUE THREAD

**Issue by scriptburn** [saintplay/vue-swatches#54]
Hi,

Is this possible to show fallback input custom color chooser dialog on a custom button click ?

**Comment by saintplay** [comment]
HI,
Yes, using `<input type="color" />` directly I guess

**Comment by scriptburn** [comment]
i mean like i have a context menu and clicking an item will trigger the color dialog just around the cursor ?

**Comment by saintplay** [comment]
You should create the `<input ref="colorRef" type="color" />` and triggering a `focus` programatically with a `ref`.
I don't see how this library can help you in this case
