### ISSUE TITLE
Can't use keyboard shortcuts to copy/paste/select-all on fallback-input-type="color"

### ISSUE THREAD

**Issue by navjeetfgmnt** [saintplay/vue-swatches#55]
Hi,
First of all thanks for this amazing library. I have recently integrated the advanced colour picker feature on my webpage and lot of users are reporting on being unable to use keyboard shortcuts to copy/paste/select-all on the input box in fallback-input mode.
This is the input I am talking about. It would be great if this can be addressed.
<img width="298" alt="Screen Shot 2020-07-23 at 12 06 14 pm" src="https://user-images.githubusercontent.com/26313981/88246173-1b88a480-ccdd-11ea-8ff4-45cef890eebf.png">

**Comment by saintplay** [comment]
Hi,
pretty much the same as #56
