### ISSUE TITLE
Default mode on fallback-input-type="color"

### ISSUE THREAD

**Issue by navjeetfgmnt** [saintplay/vue-swatches#56]
Is there a way to default to HEX on advanced colour picker.
<img width="272" alt="Screen Shot 2020-07-23 at 12 14 40 pm" src="https://user-images.githubusercontent.com/26313981/88246579-3dcef200-ccde-11ea-81c1-e55172331a3e.png">

**Comment by saintplay** [comment]
looks like a stackoverflow question, vue swatches does not control the behaviour of the fallback input

**Comment by navjeetfgmnt** [comment]
Thanks. Another question. Can we have both HEX input and html5 colour picker as fallback? Something like this
![Colour-Picker-mockup](https://user-images.githubusercontent.com/26313981/88250957-97d6b400-ccec-11ea-93ff-075ed4d7d827.jpg)

**Comment by saintplay** [comment]
No, It's not supported

**Comment by Daniel4Digital** [comment]
Would be great to have a way to set HEX as default.

**Comment by saintplay** [comment]
Closing this, since there is no way this library could change that
