### ISSUE TITLE
Label for fallback when inline

### ISSUE THREAD

**Issue by dennmat** [saintplay/vue-swatches#60]
It would be great to have a slot or even prop to add a label to the fallback selector(especially when set to color picker input) when its inline. Currently it's slightly unclear what it will do. 

![vswatches](https://user-images.githubusercontent.com/119615/96326756-67f42f80-1001-11eb-9f63-b9e02af89ca7.png)

Also if it's being used perhaps some way to indicate that it is the "selected" value. A checkmark or border styling or something.

This library is great thanks!

**Comment by saintplay** [comment]
Hi, that is a useful case, however I don't think we will add another prop to the fallback, because they are so many uses cases to cover. Instead a slot would be useful, but they were implementation challenges. For now, using a separate input is advised.
