### ISSUE TITLE
Multiple vue-swatches at the same component

### ISSUE THREAD

**Issue by lampuerov** [saintplay/vue-swatches#74]
Hello, I hope it's going well.

After reading all your closed and open issues, I didn't find anything related to this. I'm currently trying to use 2 vue-swatches at the same component, but my issue is that when one is clicked and open the other is automatically open too. 

Is there a way to handle this?.

I have realized that one of my methods, that change the size of the open box, is causing the behavior:

> changeSize() {
      $('.vue-swatches__container').attr(
        'style',
        'width: 126px; height: 164px; inset: 30px 0px 0px -100px; background-color: rgb(255, 255, 255);
        border: 0.5px solid #707070; border-radius: 2px; opacity: 1; box-shadow: none;',
      );
      $('.vue-swatches__wrapper').attr('style', 'width: 126px; margin-bottom: 5px; margin-top: 6px;');
      $('.vue-swatches__fallback__wrapper').attr(
        'style', 'width: 126px; padding-top: 20px !important; display: inline;',
      );
      $('.vue-swatches__fallback__button').attr(
        'style',
        'width: 29px; height: 20px; font: normal normal bold 9px/37px Inter; text-align: center; letter-spacing: 0px;
        opacity: 1; background-color: #2C6EEB; border-radius: 2px; align-items: center; justify-content: center;
        margin-right: 0px; color: white; width: 20%; display: inline-flex; align-items: center;
        justify-content: center; position: absolute; transform: translate(26px, 0px);',
      );
      $('.vue-swatches__fallback__button').removeClass('vue-swatches__fallback__button');
      $('.vue-swatches__fallback__input').attr(
        'style',
        'height: 13px; width: 80px; position: absolute; transform: translate(-52px, -13px);
        padding-top: 1.5px; padding-bottom: 1.5px; background-color: white; 
        border: 0.5px solid #707070; border-radius: 2px;',
      );
      $('.vue-swatches__fallback__input').removeClass('vue-swatches__fallback__input');
    },

That was the only way that I found to specify a custom style, but I'm stuck on the double open.

My 2 v-swatches instaces are:

> <v-swatches
                      id="iconColorSwatch"
                      class="mr-14"
                      :swatches="iconColors"
                      :trigger-style="triggerStyles"
                      :swatch-style="swatchStyles"
                      show-fallback
                      fallback-input-type="color"
                      v-model="iconColor"
                      @input="updateIconColor"
                      @open="changeSize()"
                      row-length="4"
                    />

> <v-swatches
                  id="containerBackgroundSwatch"
                  class="mr-8"
                  :swatches="iconColors"
                  :trigger-style="triggerStyles"
                  :swatch-style="swatchStyles"
                  show-fallback
                  fallback-input-type="color"
                  v-model="containerBackgroundColor"
                  @input="colorSelected"
                  @open="changeSize()"
                  row-length="4"
                />

Regards and thanks in advance.

**Comment by saintplay** [comment]
Hello

This code looks weird in vue, why are you using jquery?

Anyways I think you could do something like this

```js
changeSize(elementId) {
$(elementId + ' .vue-swatches__container').attr(
'style',
'width: 126px; height: 164px; inset: 30px 0px 0px -100px; background-color: rgb(255, 255, 255);
border: 0.5px solid #707070; border-radius: 2px; opacity: 1; box-shadow: none;',
);
// The same thing for the other instructions.
```

And then

```vue
<v-swatches
id="iconColorSwatch"
...
@open="changeSize('iconColorSwatch')"
/>

<v-swatches
id="containerBackgroundSwatch"
...
@open="changeSize('containerBackgroundSwatch')"
/>
```

**Comment by luisampuerovalenzuela** [comment]
Thank you very much! I'm using jquery for simplicity but I have already received recommendations to use Vanilla javascript instead. Do you have any advice to do the same in other way? Any input is welcome. 

This solution solve my issue 💯🤟🏾. Very fast response, regards.
